### ISSUE TITLE
Modify blinded attribute computation to move HMAC to the end of the process

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/edv-client#105]
Blinded attributes could be computed more efficiently if all of the HMACing (of both simple and compound indexes) can be done at the end, in parallel.

Currently, all simple attributes are blinded (HMAC'd) first. Then the resulting blind simple attributes are used to build the compound indexes. Then, finally, the compound indexes are blinded (HMAC'd). This means the final step must wait for the first step to complete, it cannot be run in parallel. This was originally designed this way prior to the addition of local hashing prior to HMACing -- to limit the size of the data that needed to be HMAC'd for compound indexes. This is no longer a concern.

The problem with making the above change is that it is a breaking change. However, it would improve performance significantly (potentially 2x or more savings) for cases where HMACing is done over a network (which is the common case with WebKMS).

**Comment by mattcollier** [comment]
@dlongley A 2X improvement sounds good, but it matters if this results in a 100ms improvement or a 1000ms improvement in a common use case.  Are you able to quantify your findings in this way?

**Comment by dlongley** [comment]
@mattcollier, it depends on the network latency between the client and the server. It cuts network wait time in half.

**Comment by dlongley** [comment]
I think a conversion function could be included with a new major version of this library that would enable applications to convert existing indexed EDV docs to the new format as an initialization step. The conversion function would take a list of any previously indexed attributes, fetch any matching docs, and convert them to use the new attribute format.

**Comment by dlongley** [comment]
Modifications in #106. Still need to add migration helper function.

**Comment by dlongley** [comment]
Addressed by #106.
