### ISSUE TITLE
Make service host/port dependencies explicit?

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/edv-client#12]
```
  const config = await EdvClient.createEdv({
      config: {
        sequence: 0,
        controller: accountId,
        keyAgreementKey: { id: keyAgreementId, type: keyAgreementType },
        hmac: { id: hmacId, type: hmacType }
      }
    });
```

I am surprised not to see an explicit connection string for the following network requests that occur in the background:

```
/edvs
/edvs
http://localhost:9876/edvs/:edvId
http://localhost:9876/edvs/:edvId/documents
http://localhost:9876/edvs/:edvId/query
http://localhost:9876/edvs/c7b47c8b-0dbd-43b8-8e04-457fdc3500f6/documents/:docId
http://localhost:9876/edvs/c7b47c8b-0dbd-43b8-8e04-457fdc3500f6/documents/:docId
http://localhost:9876/edvs/c7b47c8b-0dbd-43b8-8e04-457fdc3500f6/documents/:docId
```

In particular, `/edvs`... I think this should be `http://localhost:9876/edvs`, as this appears to be the create resource endpoint and `localhost:9876` appears to the edv-server.

Running the client without the mocks up causes `connect ECONNREFUSED 127.0.0.1:80`, but looking at the logs, I would expect the port to be 9876.

I would expect the createEdv interface to look more like this:

```
  const config = await EdvClient.createEdv({
      server: "http://localhost:9876",
      config: {
        sequence: 0,
        controller: accountId,
        keyAgreementKey: { id: keyAgreementId, type: keyAgreementType },
        hmac: { id: hmacId, type: hmacType }
      }
    });
```

This is the line that appears to be incorrect to me:

https://github.com/digitalbazaar/edv-client/blob/master/tests/MockStorage.js#L17

I would expect:

```
edvs: `${baseUrl}${root}`,
```

**Comment by dlongley** [comment]
The `createEdv` API has an optional param `url` that can be set in a similar way that your proposed `server` would be set:

```
  const config = await EdvClient.createEdv({
      url: "http://localhost:9876/edvs",
      config: {
        sequence: 0,
        controller: accountId,
        keyAgreementKey: { id: keyAgreementId, type: keyAgreementType },
        hmac: { id: hmacId, type: hmacType }
      }
    });
```

The `url` param defaults to `/edvs` for the common case of a Web application hitting its own server with the default path.

The `/edvs` path isn't hardcoded in the spec, allowing for the base path to be determined by the server. Only the subpaths (`/edvs/xxx/...`) are hardcoded per the spec.

**Comment by OR13** [comment]
haha, i just figured this out! was about to close the issue.

thanks!

**Comment by dlongley** [comment]
Sure!
