### ISSUE TITLE
Nonstandard base58 encoding dependecy?

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/edv-client#13]
https://github.com/digitalbazaar/edv-client/blob/master/baseN.js

https://github.com/cryptocoinjs/base-x

WARNING: This module is NOT RFC3548 compliant, it cannot be used for base16 (hex), base32, or base64 encoding in a standards compliant manner.

I'd rather not see this dependency bundled like this.

I'd prefer to see https://www.npmjs.com/package/multibase or basically a dependency that is in node_module, and package.json and will get updates / security patches. 

Even better would be to see an example using pem.

**Comment by OR13** [comment]
This is probably an attempt to keep the bundle size low, but it comes at the cost of raising security and standards compliance questions.

**Comment by dlongley** [comment]
@OR13 -- IIRC, the problem was that the other options were isomorphic (did not run in the browser without introducing significant and unnecessary polyfill size). We should do something like publish a `base58-universal` npm module and pull that in to resolve this issue.

**Comment by mattcollier** [comment]
v2.2.0+ uses `base58-universal` which addresses this issue.  Closing.

Landed in 2.2.0 https://github.com/digitalbazaar/edv-client/blob/master/CHANGELOG.md#220---2020-02-26
