### ISSUE TITLE
Interaction protocols on top of EDV

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/edv-client#15]
Alice creates EDV_ALICE, Bob creates EDV_BOB.

Alice and Bob discover each others DIDs, and see each others edvs from the services definitions in their docs.

Alice creates a document for interacting with Bob and delegates him write access to that document.

Bob creates a document for interacting with Alice and delegates her write access to that document.

Alice and Bob can send messages to each other by using their delegated write access.

Is this the basic interaction protocol on top of EDV or it at the EDV and not document level?

Can an EDV provide a public inbox like functionality similar to that of an email address? where anyone can send a message to the inbox?

Would it be better for Alice and Bob to create a new EDV for their relationship together?

I'm searching for a familiar analogy for EDVs, especially so I can model multiparty interactions on top of them.

**Comment by dlongley** [comment]
@OR13,

> Is this the basic interaction protocol on top of EDV or it at the EDV and not document level?

It can be either. Document level may be more common.

 > Can an EDV provide a public inbox like functionality similar to that of an email address? where anyone can send a message to the inbox?

It can be done -- but perhaps another approach is better.

> Would it be better for Alice and Bob to create a new EDV for their relationship together?

That's one approach. Another may be for Alice to create messages on her own EDV that are for Bob and then leave him anonymized zcaps to read them elsewhere, perhaps on a public blockchain. In this model, Alice has to use her own storage to create messages for Bob -- and pay to put the anonymized zcaps onto the blockchain. This can be considered an effective anti-spam mechanism that improves upon the current mess with email inboxes. Bob can read this blockchain for zcaps that have been anonymized such that only he knows that they are for him and decide whether or not he wants to pull those messages.

**Comment by csuwildcat** [comment]
In my view, Alice should be creating one logical storage/replication mesh per DID, and be able to store any objects she wants in it that are either public (plaintext), private (encrypted for only her, or permissioned (encrypted AND access-guarded for a set of external parties). If Alice wants to send a message to Bob, she should be able to look up a service endpoint and send a Bob-encrypted message to an instance of his storage/replication mesh. This probably isn't/shouldn't be a 'raw' layer like EDV, but something like a Hub that wraps that primitive layer with the intelligence required to make the inbox case a sane, doable thing without complex technical contortions.

**Comment by OR13** [comment]
This was a helpful discussion, but as I opened this issue, I'm going to close it so we can focus on the dev work needed to support this discussion which is in progress.
