### ISSUE TITLE
insert API mutates the doc

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/edv-client#21]
https://github.com/digitalbazaar/edv-client/blob/master/EdvClient.js#L114

Not a fan of mutating function parameters, does anyone else care?

**Comment by davidlehn** [comment]
I care.  `insert` adds `stream` too.  Could do a `doc = {...doc}` shallow copy if that's not too inefficient for this use case.

**Comment by mattcollier** [comment]
I'm calling this a bug, because if the mutation was a feature, then *not* mutating will be a breaking change.
