### ISSUE TITLE
Change tests to use new delegation and revocation model

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/edv-client#30]
What is presently implemented:
1. A zcap is "enabled" when delegated by storing it as an authorization
2. Submitting only the zcap ID when invoking
3. Revocation is performed by "disabling" a zcap by removing it as an authorization

Change to:
1. No need to store any "authorizations" when delegating, to enable further delegation also hand over a revocation zcap
2. Submit entire zcap when invoking
3. Use revocation zcap to revoke any delegations

**Comment by dlongley** [comment]
@mattcollier -- putting your name here so you see it. Expectation is for @aljones15 to implement.

**Comment by mattcollier** [comment]
There are tests related to the `revokeCapability` API now.  Closing this.
