### ISSUE TITLE
`headers` in the mock server is a nested object

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/edv-client#37]
https://github.com/digitalbazaar/edv-client/blob/master/tests/MockServer.js#L63

`headers` here looks like this:
```js
{
  headers: {
    accept: 'application/ld+json, application/json',
    host: 'localhost:9876',
    'capability-invocation': 'zcap id="http://localhost:9876/edvs/dbbcc174-6848-4de6-9f97-e8681752b1ef/zcaps/revocations",action="write"',
    digest: 'mh=uEiBtgvl0qAaCGFP34H3jr4xs72lLdodX-oEqV3v8jX3vUw',
    'content-type': 'application/json',
    authorization: 'Signature keyId="did:key:controller#assertionMethodId",headers="(key-id) (created) (expires) (request-target) host capability-invocation content-type digest",signature="sSVI/qlFJGbHGpStSv47OCf4O6hwaTzlx/9ofxY8IqxmaWxQLnPAnt6MthmhS+uX8cwc/41AwETdXxn/lAziAQ==",created="1582818778417",expires="1582819378417"'
  },
  httpsAgent: undefined
}
```

This results in having to inspect headers in the mock route endpoints as `request.headers.headers` which I do not believe was the intent.

**Comment by aljones15** [comment]
I can try to fix this soon. Should be fairly simple and my apologies about how bad the mock sinon server is as this is the second time it has turned out to be faulty.

**Comment by mattcollier** [comment]
This has been addressed in https://github.com/digitalbazaar/edv-client/pull/61
