### ISSUE TITLE
Use JCS when creating indexes

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/edv-client#48]
Indexing complex values should serialize them in a canonical way so that different EDV clients will be able to find the values (do not just use JSON.stringify()).

https://github.com/digitalbazaar/edv-client/blob/master/IndexHelper.js#L225

Use npm package "canonicalize" for the JCS implementation.

**Comment by mattcollier** [comment]
Code here has moved around a bit: I believe the proper line of code is now: https://github.com/digitalbazaar/edv-client/blob/master/IndexHelper.js#L326

Here's the lib that should be used:
https://www.npmjs.com/package/canonicalize
