### ISSUE TITLE
Add `count` API

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/edv-client#50]
`find` should be updated to accept a flag that specifies that a count is desired instead of returning the results. A new `count` API should use find() with this flag and just return the number of documents found that match the query. This will need to be supported in the backend server as well (pass `count: true` in the HTTP body to cause the backend to return only a count).

**Comment by aljones15** [comment]
this is cool. I'll look into it soon.

**Comment by mattcollier** [comment]
Connected with this issue on the backend. https://github.com/digitalbazaar/bedrock-edv-storage/issues/34

**Comment by mattcollier** [comment]
Landed.

**Comment by dlongley** [comment]
@mattcollier,

I just noticed that no `count` API was created. A `count` flag was added to `find`, but the second part of this issue that called for a `count` API to be created didn't happen. I'm re-opening because I'm mostly curious to know if that was an intentional decision or if this was just missed. If it was intentional, please close.

**Comment by dlongley** [comment]
The `count` API would take the same inputs as find but also destructure the response `{count: <number>}` so that only a number is returned. Similar to mongodb's count API.

**Comment by mattcollier** [comment]
@dlongley OK, but that's just a convenience method right?  Which is a wrapper around the find API?  That's why it was left out.  I figured the find method with the count was adequate, but the wrapper is fine if that is what you would like.

**Comment by dlongley** [comment]
Yeah, it's a wrapper. I think it's cleaner to be able to call `count({...})` and just get back a number. +1 to a `count` API wrapper.

**Comment by dlongley** [comment]
Is this done? If so, please close.

**Comment by mattcollier** [comment]
Landed: https://github.com/digitalbazaar/edv-client/blob/master/CHANGELOG.md#310---2020-06-10
