### ISSUE TITLE
Should deriveSecret hash the result of scalar multiplication?

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/edv-client#64]
https://github.com/digitalbazaar/x25519-key-pair/blob/master/lib/X25519KeyPair.js#L295
https://github.com/StableLib/stablelib/blob/master/packages/x25519/x25519.ts#L613

The Mocks implies no, and so does X25519KeyPair, however StableLib implies yes.

https://crypto.stackexchange.com/questions/38006/security-model-scalar-multiplication-in-nacl

**Comment by dlongley** [comment]
@OR13, the result of `deriveSecret` should be fed into a KDF. For JWEs using `ECDH-ES+A256KW`, there's a specific KDF (a specific profile of "concat" from NIST) that is used, see [RDC 7518](https://tools.ietf.org/html/rfc7518).

The implementation used here by edv-client can be found here:
https://github.com/digitalbazaar/minimal-cipher/blob/master/algorithms/ecdhkdf.js#L30-L85

So, in short, the raw secret is not used directly, rather it is used as one of several parameters for a standardized KDF per the JWA spec for `ECDH-ES+A256KW`.

**Comment by OR13** [comment]
@dlongley thanks, this makes sense now. I was wondering if X25519KeyPair should be offering a higher level API for encryption, and in particular, I was comparing X25519KeyPair with https://github.com/digitalbazaar/edv-client/blob/master/tests/MockKak.js

something like a blend of X25519KeyPair and minimal cipher... given that `deriveSecret` feeds into `ECDH-ES+A256KW` and is not used directly by itself... such an API would also feel similar to the raw vanilla lib sodium interface: https://doc.libsodium.org/public-key_cryptography/authenticated_encryption

something like:

```
key1 = X25519KeyPair.generate({...});
const jwe = key1.encryptFor({message, publicKey, {alg: 'ECDH-ES+A256KW'} });
```

**Comment by dlongley** [comment]
Hmm, I think it's better to keep things separated so they can be minimized. There's more than one use for these things. But, perhaps what we should do is update the appropriate READMEs showing how to use libraries together.

**Comment by OR13** [comment]
@dlongley yes, @tplooker and I had a good conversation about this.

I think there is probably a case to be made for JsonWebKey2020 that JWE, JWS and deriverSecret support could ship with the key class, but thats more of a reflection of what a JOSE developer would expect, and has nothing to do with deriveSecret in a general sense.

A related question:

Does RDF have the concept of OOP interfaces?

X25519KeyPair only supports deriveSecret
Ed25519KeyPair only supports sign / verify
P-384KeyPair would support both...

when these classes are exposed semantically, it feels like `X25519KeyAgreementKey2019` is actually of interface IKeyAgreement with one required to implement member deriveSecret.

But what happens when I put P-384 next to it in keyAgreement section of did document?

as long as that one required to implement interface is there it should be fine...

when we get the JSON-LD Security Group started, I would love to take a stab at formalizing some of these interfaces, and types...I think this would also help get implementations of linked data signatures off the ground faster in other langauges.

**Comment by dlongley** [comment]
> Does RDF have the concept of OOP interfaces?

Well, you can model any concept in RDF... but I know you're asking for specific vocabularies here. There isn't anything in [RDF Schema](https://www.w3.org/TR/rdf-schema/) for this, but I did find this:

https://fno.io/spec/

There is also [Hydra](http://www.hydra-cg.com/spec/latest/core/), but that's for Web APIs.

> when we get the JSON-LD Security Group started, I would love to take a stab at formalizing some of these interfaces, and types...I think this would also help get implementations of linked data signatures off the ground faster in other langauges.

+1

This would also be related to the WebKMS work -- having formal APIs for these sorts of keys that can be invoked via HTTP or JS interfaces.

**Comment by dlongley** [comment]
Closing as stale and perhaps nothing actionable. Feel free to reopen if necessary.
