### ISSUE TITLE
Complete axios to @digitalbazaar/http-client conversion

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/edv-client#69]
A start on this has been made here:

https://github.com/digitalbazaar/edv-client/pull/61

Need to implement a streams API in http-client to be used here.

**Comment by JSAssassin** [comment]
@mattcollier can you please provide some more information on this issue, what the new `streams API` in @digitalbazaar/http-client should do and also point where it will be used in the edv-client?

**Comment by mattcollier** [comment]
@aljones15 you've done some work along these lines correct?  Can you add any guidance here?

**Comment by mattcollier** [comment]
@JSAssassin I see that https://github.com/digitalbazaar/edv-client/pull/61 was merged and that axios is no longer a dependency here: https://github.com/digitalbazaar/edv-client/blob/master/package.json#L26-L34  

I am closing this issue now.
