### ISSUE TITLE
Consider sending stream sequence and number of chunks to server

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/edv-client#78]
If we remove this line that deletes the stream sequence and number of chunks:

https://github.com/digitalbazaar/edv-client/blob/6bdadb3999140fed1fd9fa33ebc7c9c29e649d4d/EdvClient.js#L1092

We could transmit this information to the server, which is useful for replication and archival purposes. The server can already determine the sequence number and number of chunks if it pays attention to writes to chunk indexes out of band, so this is not technically extra knowledge, it is just more conveniently "in band". We should be careful not to send content hashes to the server if/when we implement those in the stream meta data -- unless those hashes are on the encrypted data.

cc: @dmitrizagidulin, @msporny 

What are your thoughts @OR13? We may make this (breaking) change soon and include this information in a new major release of the client.

**Comment by OR13** [comment]
@dlongley we and secure key have not implemented streams yet, so the more breaking changes you can make before that, the better :)

I am not sure of the implications, but it sounds like this is metadata that the server should have, and there is no reason for the client not to send it.

I am not sure about the comment regarding ciphertext digests, is the idea that the client would compute the digest and send the digest along with the chunks? isn't this redundant given the http digest header?

**Comment by dlongley** [comment]
> I am not sure about the comment regarding ciphertext digests, is the idea that the client would compute the digest and send the digest along with the chunks? isn't this redundant given the http digest header?

Yes, I think this would be more about digests on plaintext -- I just want to make sure that we're careful about what we send up as string meta data. We should be explicit in what gets sent rather than forwarding along whatever is in `stream`.

@dmitrizagidulin -- we should proceed with implementing this when we have time. We should replace deleting `stream` by instead setting it to contain the sequence and number of chunks (the two fields that are currently present, but we should explicitly list them out so if we add other fields in the future they don't get sent without a review).

**Comment by OR13** [comment]
worth noting that digests of plaintext is a feature that @cswildcat is interested in for hubs.

in particular that the digest of the initial plaintext might be an acceptable identifier for the document.

**Comment by dmitrizagidulin** [comment]
Addressed by PR #80 and PR https://github.com/digitalbazaar/bedrock-edv-storage/pull/69. Closing.
