### ISSUE TITLE
Stream in incorrect namespace.

### ISSUE THREAD

**Issue by tolson4** [digitalbazaar/edv-client#79]
Looks like the stream in `EdvClient.update`
https://github.com/digitalbazaar/edv-client/blob/6bdadb3999140fed1fd9fa33ebc7c9c29e649d4d/EdvClient.js#L249-L252

was not included as part of this commit https://github.com/digitalbazaar/edv-client/commit/1cdbbadb4e26a92bca8636f721725c682aa683b7

**Comment by dmitrizagidulin** [comment]
Thanks @tolson4! Fixed in PR #80.
