### ISSUE TITLE
Edv Client imports a library it does not require in package.json

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/edv-client#83]
https://github.com/digitalbazaar/edv-client/blob/14f4ba7d9cc0ea8622f9822771adfea5dbd1f789/util.js#L3

`web-streams-polyfill` is a depdenency in `minimal-cipher`, but not in edv client itself:

https://github.com/digitalbazaar/edv-client/blob/14f4ba7d9cc0ea8622f9822771adfea5dbd1f789/package.json#L26-L74

hence creating a situation where if `minimal-cipher` were to remove or change that dependency, `util.js` would fail.

Solutions:

1. require `web-streams-polyfill` in `edv-client` itself
2. add `web-streams-poyfill` as a `peerDependency`
3. Something brilliant I have not considered

**Comment by dlongley** [comment]
Since we're using it directly in this library, we should include it as a dependency.

**Comment by JSAssassin** [comment]
Closing, this was implemented.
