### ISSUE TITLE
Make _getChunk, _storeChunk, _updateStream helpers public APIs

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/edv-client#85]
https://github.com/digitalbazaar/edv-client/blob/master/EdvClient.js#L1204
https://github.com/digitalbazaar/edv-client/blob/master/EdvClient.js#L1175
https://github.com/digitalbazaar/edv-client/blob/master/EdvClient.js#L1119

We see that EDV implementers would like to have access to this API.

**Comment by dlongley** [comment]
The chunk APIs are available via transport interfaces now. Closing as stale / perhaps addressed or no longer needed.
